[project]
name = "zippy-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
    "discord>=2.3.2",
    "flask>=3.1.1",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.10",
]
